[package]
name = "todoclient"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
leptos = "0.2.3"
log = "0.4.17"
reqwasm = "0.5.0"
serde = "1.0.157"
