[package]
name = "todoclient"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
extension-trait = "1.0.1"
js-sys = "0.3.61"
leptos = "0.2.3"
log = "0.4.17"
reqwasm = "0.5.0"
serde = "1.0.157"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
web-sys = "0.3.61"
